# Generated by Django 3.2 on 2023-07-28 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media')),
                ('mobile_money_number', models.CharField(max_length=20)),
                ('transaction_screenshot', models.ImageField(blank=True, null=True, upload_to='media/screenshoot')),
            ],
        ),
    ]
