# Generated by Django 4.2.5 on 2023-09-25 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobus", "0002_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="applyjob",
            name="letter",
            field=models.TextField(default=""),
        ),
    ]
