# Generated by Django 4.2.5 on 2023-09-25 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("jobus", "0003_applyjob_letter"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="company_name",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="image",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="mobile_money_number",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="transaction_screenshot",
        ),
        migrations.AddField(
            model_name="payment",
            name="amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="payment",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="payment",
            name="screenshot",
            field=models.ImageField(default="none", upload_to="payment_screenshots/"),
        ),
        migrations.AddField(
            model_name="payment",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
