# Generated by Django 3.2 on 2023-07-25 19:52

from django.db import migrations, models
import resume_cv.models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_cv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=resume_cv.models.resume_cv_directory_path)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200)),
                ('experience_title', models.CharField(blank=True, max_length=100, null=True)),
                ('experience_company', models.CharField(blank=True, max_length=100, null=True)),
                ('experience_start_date', models.DateField(blank=True, null=True)),
                ('experience_end_date', models.DateField(blank=True, null=True)),
                ('experience_description', models.TextField(blank=True, null=True)),
                ('education_degree', models.CharField(blank=True, max_length=100, null=True)),
                ('education_institution', models.CharField(blank=True, max_length=100, null=True)),
                ('education_start_date', models.DateField(blank=True, null=True)),
                ('education_end_date', models.DateField(blank=True, null=True)),
                ('skills', models.TextField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='resumecvtemplate',
            name='category',
        ),
        migrations.DeleteModel(
            name='ResumeCv',
        ),
        migrations.DeleteModel(
            name='ResumeCvCategory',
        ),
        migrations.DeleteModel(
            name='ResumeCvTemplate',
        ),
    ]
